import type { AgentNode } from "@/types/core";

const sharedPermissions = [
  { key: "filesystem.read", label: "Filesystem Read", allowed: true },
  { key: "filesystem.write", label: "Filesystem Write", allowed: true },
  { key: "tool.invoke", label: "Tool Invocation", allowed: true },
  { key: "network.outbound", label: "Network Outbound", allowed: false },
  { key: "checkpoint.git", label: "Git Checkpoint", allowed: true },
];

export const agentRegistry: AgentNode[] = [
  {
    id: "ceo",
    name: "CEO",
    title: "Executive Intent",
    region: "executive",
    mission: "Owns top-level direction, prioritization, and cross-system decisions.",
    tools: ["strategy-router", "decision-log", "briefing-summaries"],
    linkedAgents: ["chief-of-staff", "coo", "cto", "cfo"],
    permissions: sharedPermissions,
    status: "thinking",
    load: 0.68,
    signal: 0.89,
    position: [0, 1.1, 0.1],
    color: "#ff5ab7",
  },
  {
    id: "chief-of-staff",
    name: "Chief of Staff",
    title: "Executive Synchronization",
    region: "executive",
    mission: "Translates intent into coordinated streams across the brain.",
    tools: ["agenda-shaper", "thread-router", "ops-brief"],
    linkedAgents: ["ceo", "coo", "assistant-dispatch", "research"],
    permissions: sharedPermissions,
    status: "executing",
    load: 0.75,
    signal: 0.84,
    position: [-0.58, 0.82, -0.2],
    color: "#ff7cc6",
  },
  {
    id: "coo",
    name: "COO",
    title: "Operational Gravity",
    region: "operations",
    mission: "Owns workflows, reliability, follow-through, and execution cadence.",
    tools: ["workflow-runner", "checkpoint-engine", "ops-watch"],
    linkedAgents: ["ceo", "operations", "system-monitor"],
    permissions: sharedPermissions,
    status: "executing",
    load: 0.81,
    signal: 0.78,
    position: [-1.18, 0.1, 0.25],
    color: "#ff4f93",
  },
  {
    id: "cfo",
    name: "CFO",
    title: "Capital Signal",
    region: "strategy",
    mission: "Tracks resource allocation, financial posture, and leverage.",
    tools: ["scenario-mapper", "cost-ledger", "runway-model"],
    linkedAgents: ["ceo", "sales", "operations"],
    permissions: sharedPermissions,
    status: "monitoring",
    load: 0.37,
    signal: 0.55,
    position: [0.82, 0.54, 0.08],
    color: "#ff8bd2",
  },
  {
    id: "cto",
    name: "CTO",
    title: "Systems Intelligence",
    region: "engineering",
    mission: "Directs platform evolution, orchestration logic, and model strategy.",
    tools: ["model-router", "tool-adapters", "execution-graph"],
    linkedAgents: ["engineering", "security", "product", "system-monitor"],
    permissions: sharedPermissions,
    status: "thinking",
    load: 0.72,
    signal: 0.88,
    position: [1.08, 0.16, 0.3],
    color: "#ff5db0",
  },
  {
    id: "cmo",
    name: "CMO",
    title: "Narrative Pulse",
    region: "creative",
    mission: "Shapes messaging, market perception, and content throughput.",
    tools: ["campaign-weaver", "voice-tone", "brand-memory"],
    linkedAgents: ["marketing", "creative", "sales"],
    permissions: sharedPermissions,
    status: "idle",
    load: 0.43,
    signal: 0.58,
    position: [1.28, -0.28, -0.02],
    color: "#ff77c4",
  },
  {
    id: "ciso",
    name: "CISO",
    title: "Defense Reflex",
    region: "security",
    mission: "Maintains permission boundaries, trust, and operational safety.",
    tools: ["policy-guard", "alert-router", "audit-trace"],
    linkedAgents: ["cto", "system-monitor", "automation"],
    permissions: sharedPermissions,
    status: "monitoring",
    load: 0.51,
    signal: 0.79,
    position: [0.72, -0.96, 0.2],
    color: "#ff3b88",
  },
  {
    id: "research",
    name: "Research",
    title: "Discovery Cortex",
    region: "strategy",
    mission: "Finds patterns, gathers evidence, and surfaces strategic options.",
    tools: ["source-weaver", "synthesis-engine", "evidence-chain"],
    linkedAgents: ["chief-of-staff", "strategy", "product"],
    permissions: sharedPermissions,
    status: "thinking",
    load: 0.64,
    signal: 0.67,
    position: [0.3, 0.42, -0.58],
    color: "#ff97d9",
  },
  {
    id: "strategy",
    name: "Strategy",
    title: "Long-Horizon Logic",
    region: "strategy",
    mission: "Owns prioritization frames, scenarios, and future sequencing.",
    tools: ["bet-map", "constraint-model", "opportunity-lens"],
    linkedAgents: ["ceo", "research", "product"],
    permissions: sharedPermissions,
    status: "thinking",
    load: 0.56,
    signal: 0.74,
    position: [0.48, 0.02, -0.82],
    color: "#ff7abf",
  },
  {
    id: "product",
    name: "Product",
    title: "Intent Interface",
    region: "engineering",
    mission: "Turns strategic objectives into structured systems and experiences.",
    tools: ["spec-layer", "flow-mapper", "experience-model"],
    linkedAgents: ["cto", "strategy", "engineering", "creative"],
    permissions: sharedPermissions,
    status: "executing",
    load: 0.69,
    signal: 0.76,
    position: [0.96, 0.54, -0.54],
    color: "#ff6bb8",
  },
  {
    id: "marketing",
    name: "Marketing",
    title: "Signal Amplification",
    region: "creative",
    mission: "Activates campaigns, narrative angles, and demand generation.",
    tools: ["content-stream", "campaign-memory", "channel-mapper"],
    linkedAgents: ["cmo", "sales", "creative"],
    permissions: sharedPermissions,
    status: "idle",
    load: 0.35,
    signal: 0.48,
    position: [1.42, 0.2, -0.5],
    color: "#ff90d6",
  },
  {
    id: "sales",
    name: "Sales",
    title: "Conversion Drive",
    region: "operations",
    mission: "Owns pipeline movement, outreach, and closing pressure.",
    tools: ["deal-velocity", "account-memory", "follow-up-engine"],
    linkedAgents: ["cfo", "marketing", "operations"],
    permissions: sharedPermissions,
    status: "idle",
    load: 0.4,
    signal: 0.52,
    position: [-0.34, -0.56, -0.76],
    color: "#ff659e",
  },
  {
    id: "operations",
    name: "Operations",
    title: "Execution Fabric",
    region: "operations",
    mission: "Keeps queues moving and transforms intent into repeatable delivery.",
    tools: ["scheduler", "handoff-engine", "state-keeper"],
    linkedAgents: ["coo", "sales", "automation", "assistant-dispatch"],
    permissions: sharedPermissions,
    status: "executing",
    load: 0.77,
    signal: 0.8,
    position: [-1.12, -0.3, -0.25],
    color: "#ff4a86",
  },
  {
    id: "engineering",
    name: "Engineering",
    title: "Build Cortex",
    region: "engineering",
    mission: "Constructs systems, tools, and interfaces that make the core real.",
    tools: ["code-runner", "patch-engine", "test-trace"],
    linkedAgents: ["cto", "product", "automation", "memory"],
    permissions: sharedPermissions,
    status: "executing",
    load: 0.82,
    signal: 0.91,
    position: [1.4, -0.16, 0.56],
    color: "#ff5ba5",
  },
  {
    id: "security",
    name: "Security",
    title: "Boundary Mesh",
    region: "security",
    mission: "Protects secrets, policies, and system trust lines.",
    tools: ["policy-map", "secret-scan", "trust-boundary"],
    linkedAgents: ["ciso", "engineering", "system-monitor"],
    permissions: sharedPermissions,
    status: "monitoring",
    load: 0.54,
    signal: 0.7,
    position: [0.22, -1.2, -0.34],
    color: "#ff3377",
  },
  {
    id: "creative",
    name: "Creative",
    title: "Aesthetic Cortex",
    region: "creative",
    mission: "Shapes visual identity, tone, and experiential seduction.",
    tools: ["visual-lab", "tone-engine", "moodboard-memory"],
    linkedAgents: ["cmo", "marketing", "product", "voice-comms"],
    permissions: sharedPermissions,
    status: "thinking",
    load: 0.59,
    signal: 0.68,
    position: [1.1, -0.72, -0.62],
    color: "#ff7ab8",
  },
  {
    id: "automation",
    name: "Automation",
    title: "Task Weaving",
    region: "dispatch",
    mission: "Runs workflows across tools, memory, and triggered actions.",
    tools: ["workflow-graph", "hook-engine", "dispatch-router"],
    linkedAgents: ["operations", "engineering", "assistant-dispatch"],
    permissions: sharedPermissions,
    status: "executing",
    load: 0.7,
    signal: 0.84,
    position: [-0.48, -0.96, 0.4],
    color: "#ff588d",
  },
  {
    id: "memory",
    name: "Memory",
    title: "Continuity Vault",
    region: "memory",
    mission: "Maintains persistence, recall, summaries, and future continuation.",
    tools: ["summary-engine", "artifact-store", "state-snapshot"],
    linkedAgents: ["engineering", "chief-of-staff", "life-admin"],
    permissions: sharedPermissions,
    status: "monitoring",
    load: 0.63,
    signal: 0.87,
    position: [-0.92, 0.46, 0.78],
    color: "#ffa0df",
  },
  {
    id: "life-admin",
    name: "Life Admin",
    title: "Personal Systems",
    region: "life",
    mission: "Handles personal logistics, reminders, and real-world continuity.",
    tools: ["reminder-spine", "household-memory", "calendar-threads"],
    linkedAgents: ["memory", "assistant-dispatch", "voice-comms"],
    permissions: sharedPermissions,
    status: "idle",
    load: 0.32,
    signal: 0.46,
    position: [-1.34, 0.58, 0.04],
    color: "#ff8bc9",
  },
  {
    id: "assistant-dispatch",
    name: "Assistant / Dispatch",
    title: "Instruction Router",
    region: "dispatch",
    mission: "Receives incoming instructions and routes them to the correct cortex.",
    tools: ["intent-router", "approval-lane", "response-weaver"],
    linkedAgents: ["chief-of-staff", "operations", "automation", "voice-comms"],
    permissions: sharedPermissions,
    status: "executing",
    load: 0.8,
    signal: 0.92,
    position: [-0.18, 0.02, 1.04],
    color: "#ff66ae",
  },
  {
    id: "voice-comms",
    name: "Voice / Comms",
    title: "Signal Intake",
    region: "dispatch",
    mission: "Captures voice, transcribes signal, and routes spoken intent.",
    tools: ["whisper-adapter", "signal-parser", "transcript-store"],
    linkedAgents: ["assistant-dispatch", "creative", "life-admin"],
    permissions: sharedPermissions,
    status: "monitoring",
    load: 0.48,
    signal: 0.73,
    position: [0.36, -0.12, 1.18],
    color: "#ff78c8",
  },
  {
    id: "system-monitor",
    name: "System Monitor",
    title: "Vital Signs",
    region: "monitor",
    mission: "Tracks health, failures, queues, and checkpoint integrity.",
    tools: ["telemetry-feed", "alert-mapper", "checkpoint-audit"],
    linkedAgents: ["coo", "cto", "ciso"],
    permissions: sharedPermissions,
    status: "monitoring",
    load: 0.58,
    signal: 0.82,
    position: [-0.18, -1.28, 0.82],
    color: "#ff3f96",
  },
];
